Update demo.yaml

diff --git a/.github/workflows/demo.yaml b/.github/workflows/demo.yaml
--- a/.github/workflows/demo.yaml
+++ b/.github/workflows/demo.yaml
@@ -31,12 +31,12 @@ jobs:
           echo "aaa"
           
       - name: If release name set, verify it corresponds correctly to tag
-        if: ${{ github.event.release.name }} != Null && ${{ github.event.release.name }} != ${{ env.VERSION }}
+        if: ${{ github.event.release.name != '' && github.event.release.name != env.VERSION }}
         run: |
-          echo "Release name is not null and the release name is not equivalent to env version."
+          echo "Release name is not empty and release name is not equivalent to version."
+          echo "Failing job."
+          exit 1
           
-        
-        
         
       - name: Update release name
         id: update_release
